#index:
#    path: /
#    controller: App\Controller\DefaultController::index
app.admin.custompage.menu:
    path: /custom/page
    defaults:
        _controller: App\Controller\CustomPageController::view
